force-app/main/default/objects/DebugEntry__c/DebugEntry__c.object-meta.xml
<CustomObject>
    <description>Used to store debug information coming from ApexClasses</description>
    <label>Debug Entry</label>
    <nameField>
        <displayFormat>Debug-{000000}</displayFormat>
        <label>Debug Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DebugEntry__c/fields/className__c.field-meta.xml
<CustomField>
    <fullName>className__c</fullName>
    <description>This DebugEntry has been created in the context of Class Name</description>
    <inlineHelpText>This class created this debug entry</inlineHelpText>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DebugEntry__c/fields/Column__c.field-meta.xml
<CustomField>
    <fullName>Column__c</fullName>
    <description>Column in source code this Entry originates from</description>
    <inlineHelpText>Column in source code this Entry originates from</inlineHelpText>
    <label>Code Column</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DebugEntry__c/fields/cpuTimeUsage__c.field-meta.xml
<CustomField>
    <fullName>cpuTimeUsage__c</fullName>
    <description>stores the cpu time used of the whole transaction</description>
    <inlineHelpText>This is the CPU used by the transaction</inlineHelpText>
    <label>CPU Time Usage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DebugEntry__c/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <description>Line in source code from which this Entry originates</description>
    <inlineHelpText>Line in source code from which this Entry originates</inlineHelpText>
    <label>Code Line</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DebugEntry__c/fields/logEntryJSON__c.field-meta.xml
<CustomField>
    <fullName>logEntryJSON__c</fullName>
    <description>Contains the JSON of a Log Entry Array</description>
    <inlineHelpText>Please ignore if this is visible to you.</inlineHelpText>
    <label>Log Entry JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DebugEntry__c/fields/methodName__c.field-meta.xml
<CustomField>
    <fullName>methodName__c</fullName>
    <description>The method in context when this debug entry was created</description>
    <inlineHelpText>Method from which this entry was created</inlineHelpText>
    <label>methodName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DebugEntry__c/fields/runningUser__c.field-meta.xml
<CustomField>
    <fullName>runningUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The context/running user of the class responsible for this DebugEntry</description>
    <inlineHelpText>Who dun it?</inlineHelpText>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DebugEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DebugEntry__c/fields/startDateTime__c.field-meta.xml
<CustomField>
    <fullName>startDateTime__c</fullName>
    <description>Indicates startDateTime of the transaction that leads to the sending of this log event.</description>
    <inlineHelpText>When did this occur?</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__e/Log__e.object-meta.xml
<CustomObject>
    <description>Subscribers of this event will receive updates on Logger events</description>
    <label>Log</label>
    <pluralLabel>Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log__e/fields/clusterId__c.field-meta.xml
<CustomField>
    <fullName>clusterId__c</fullName>
    <description>JSONs of clustered Events will be saved as attachment</description>
    <label>Cluster Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/isException__c.field-meta.xml
<CustomField>
    <fullName>isException__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates log event was raised during an exception</description>
    <label>is Exception</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/LogEntriesJSON__c.field-meta.xml
<CustomField>
    <fullName>LogEntriesJSON__c</fullName>
    <description>Is expected to contain a JSON of a List&lt;Logger.LogEntry></description>
    <label>LogEntries JSON</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/startDateTime__c.field-meta.xml
<CustomField>
    <fullName>startDateTime__c</fullName>
    <description>Indicates startDateTime of the transaction that leads to the sending of this log event.</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Trace__c.field-meta.xml
<CustomField>
    <fullName>Trace__c</fullName>
    <description>contains current trace in format className:methodName:line:column</description>
    <label>Trace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DebugEntryService.cls
public with sharing class DebugEntryService {
    
    public static void saveLogs(List<Log__e> logs) {
        //
        List<DebugEntry__c> newDebugEntries = new List<DebugEntry__c>();
        List<DebugEntry__c> debugEntriesToInsert = new List<DebugEntry__c>();
        List<Log__e> clusteredLogs = new List<Log__e>();
        // no clusterId
        // clusterId 	
        For (Log__e log: logs) {
            if(!isValid(log.Trace__c.split(':'))) {
                return;
            }
            if(log.clusterId__c == null) {
                newDebugEntries.add(convertLogToDebugEntry(log));
            } else {
                clusteredLogs.add(log);
            }
            
            if (AppConfigSupport.saveAllLogs) {
                debugEntriesToInsert.addAll(newDebugEntries);
            } else if (AppConfigSupport.saveExceptionLogs) {
                for (DebugEntry__c entry : newDebugEntries) {
                    if (entry.isException__c) {
                        debugEntriesToInsert.add(entry);
                    }
                }    
            }
            
        }
        
        insert debugEntriesToInsert;
    }
    
    @testvisible
    private static Boolean isValid(List<String> traceInfo) {
        return traceInfo != null && traceInfo.size()==6;
    }
    
    private static DebugEntry__c convertLogToDebugEntry(Log__e log) {
        List<String> traceInfo = log.Trace__c.split(':');
        DebugEntry__c entry = new DebugEntry__c(className__c = traceInfo[0],
                                                methodName__c = traceInfo[1],
                                                Line__c = Integer.ValueOf(traceInfo[2]),
                                                Column__c = Integer.ValueOf(traceInfo[3]),
                                                cpuTimeUsage__c = Integer.ValueOf(traceInfo[4]),
                                                runningUser__c = traceInfo[5],
                                                startDateTime__c = log.startDateTime__c,
                                                logEntryJSON__c = log.LogEntriesJSON__c,
                                                isException__c = log.isException__c
                                               );
        return entry; 
    }
    
    @testvisible
    private static void convertLogClusterToDebugEntry(List<Log__e> logClusters) {
        
    }
    
    @testvisible
    private static Map<String,List<Log__e>> getClustersMap(List<Log__e> logClusters) {
        Map<String,List<Log__e>> clustersMap = new Map<String,List<Log__e>>();
        return clustersMap;
    }
    
    
}