force-app/main/default/objects/DebugEntry__c/DebugEntry__c.object-meta.xml
<CustomObject>
    <description>Used to store debug information coming from ApexClasses</description>
    <label>Debug Entry</label>
    <nameField>
        <displayFormat>Debug-{000000}</displayFormat>
        <label>Debug Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DebugEntry__c/fields/cpuTimeUsage__c.field-meta.xml
<CustomField>
    <fullName>cpuTimeUsage__c</fullName>
    <description>stores the cpu time used of the whole transaction</description>
    <inlineHelpText>This is the CPU used by the transaction</inlineHelpText>
    <label>CPU Time Usage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DebugEntry__c/fields/logEntryJSON__c.field-meta.xml
<CustomField>
    <fullName>logEntryJSON__c</fullName>
    <description>Contains the JSON of a Log Entry Array</description>
    <inlineHelpText>Please ignore if this is visible to you.</inlineHelpText>
    <label>Log Entry JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DebugEntry__c/fields/startDateTime__c.field-meta.xml
<CustomField>
    <fullName>startDateTime__c</fullName>
    <description>Indicates startDateTime of the transaction that leads to the sending of this log event.</description>
    <inlineHelpText>When did this occur?</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__e/Log__e.object-meta.xml
<CustomObject>
    <description>Subscribers of this event will receive updates on Logger events</description>
    <label>Log</label>
    <pluralLabel>Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log__e/fields/clusterId__c.field-meta.xml
<CustomField>
    <fullName>clusterId__c</fullName>
    <description>JSONs of clustered Events will be saved as attachment</description>
    <label>Cluster Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/ClusterSequence__c.field-meta.xml
<CustomField>
    <fullName>ClusterSequence__c</fullName>
    <description>if clustered, stores the position of the event in the cluster</description>
    <label>Cluster Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/LogEntriesJSON__c.field-meta.xml
<CustomField>
    <fullName>LogEntriesJSON__c</fullName>
    <description>Is expected to contain a JSON of a List&lt;Logger.LogEntry></description>
    <label>LogEntries JSON</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/startDateTime__c.field-meta.xml
<CustomField>
    <fullName>startDateTime__c</fullName>
    <description>Indicates startDateTime of the transaction that leads to the sending of this log event.</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Trace__c.field-meta.xml
<CustomField>
    <fullName>Trace__c</fullName>
    <description>contains current trace in format className:methodName:line:column</description>
    <label>Trace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DebugEntryServiceTest.cls
@isTest
private class DebugEntryServiceTest {
    
    private static List<Log__e> getLogs() {
        List<Log__e> logs = new List<Log__e>();
        logs.add(getLog('firstCluster',0,'{},'));
        logs.add(getLog('secondCluster',4,'{},'));
        logs.add(getLog('firstCluster',1,'{},'));
        logs.add(getLog('firstCluster',2,'{},'));
        logs.add(getLog('secondCluster',0,'{},'));
        logs.add(getLog('firstCluster',4,'{},'));
        logs.add(getLog('secondCluster',2,'{},'));
        logs.add(getLog('secondCluster',1,'{},'));
        return logs;
    }
    
    private static Log__e getLog(String clusterId, Integer clusterSequence, String json) {
        Log__e logEvent = new Log__e(Trace__c = 'DebugEntryServiceTest.getLog()',
                                     clusterId__c = clusterId,
                                     clusterSequence__c = clusterSequence,
                                     LogEntriesJSON__c = json,
                                     startDateTime__c = system.now()
                                    );
        return logEvent;
    }
    
    @isTest
    private static void getClustersMap_Success() {
    	List<Log__e> logs = getLogs();
        System.assert(DebugEntryService.getClustersMap(logs)!=null,'valid return expected');
        System.assertEquals(2,DebugEntryService.getClustersMap(logs).keySet().size(),'2 clusters expected');
	}
    // for several logs ONE debug entry must be created if clusterId present !!
    // create a test case with two clusterIds, each id having 4 log entries in non linear sequence
    // assert only two debugentries are created, attachment name = clusterId, store attachmentId on debugEntry__c
    // //todo below needs to be refactored after debugentry service adaption
    //    List<debugEntry__c> entries = [SELECT LogEntryJSON__c, 
    //                                          cpuTimeUsage__c,
    //                                  		  clusterId__c
    //                                          FROM DebugEntry__c Limit 1000];
    //    System.assertEquals(1, entries.size(),'More than one debug entry inserted');
    //    System.assertNotEquals(null, entries[0].clusterId__c,'Cluster Id needs to be present');
}