force-app/main/default/objects/LoggerConfig__mdt/LoggerConfig__mdt.object-meta.xml
<CustomObject>
    <description>Stores configuration for logging. Logging is generally enabled, if at least one active rule exists.</description>
    <label>Logger Configuration</label>
    <pluralLabel>Logger Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/LoggerConfig__mdt/fields/AdditionalClassNames__c.field-meta.xml
<CustomField>
    <fullName>AdditionalClassNames__c</fullName>
    <description>Additional Classes to write logs for.</description>
    <inlineHelpText>Works only if Save Behaviour is set to &#39;For Classes&#39;. Additional Classes to write logs for.</inlineHelpText>
    <label>Additional Class Names</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LoggerConfig__mdt/fields/ClassNames__c.field-meta.xml
<CustomField>
    <fullName>ClassNames__c</fullName>
    <description>Classes to write logs for.</description>
    <inlineHelpText>Works only if Logs To Save is set to &#39;For Classes&#39;. Classes to write logs for. If 255 characters are not enough, use &#39;Additional Classes to Log&#39;</inlineHelpText>
    <label>Apex Classes to Log</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LoggerConfig__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If at least one active rule exists, logging is enabled.</description>
    <inlineHelpText>Disable if you want to ignore this rule. If all rules are de-activated, logging is disabled.</inlineHelpText>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LoggerConfig__mdt/fields/LogsToSave__c.field-meta.xml
<CustomField>
    <fullName>LogsToSave__c</fullName>
    <description>Determines whether all logs, exception logs only or only logs for users with custom permission &#39;enableLogging&#39;</description>
    <inlineHelpText>Determines whether all logs, exception logs only or only logs for users with custom permission &#39;enableLogging&#39;</inlineHelpText>
    <label>Logs to save</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>AllLogs</fullName>
                <label>All Logs</label>
            </value>
            <value>
                <fullName>ExceptionsOnly</fullName>
                <label>Exceptions Only</label>
            </value>
            <value>
                <fullName>UserLogs</fullName>
                <label>User Logs</label>
            </value>
            <value>
                <fullName>For Class</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoggerConfig.cls
public with sharing class LoggerConfig {

	public Boolean enableLogging { public get; private set;}
	public Boolean saveExceptionLogs {public get; private set;}
	public Boolean saveAllLogs { public get; private set;}
	public Boolean saveUserLogs { public get; private set;}
	public String classNamesToLog {public get; private set;}

	// used for easier testing
	@testvisible private static Boolean enableLoggingOverride = false;
	@testvisible private static Boolean saveExceptionLogsOverride = false;
	@testvisible private static Boolean saveAllLogsOverride = false;
	@testvisible private static Boolean saveUserLogsOverride = false;
	@testvisible private static String classNamesToLogOverride = '';

	private static LoggerConfig loggerConfigInstance;

	private LoggerConfig() {
		if (Test.isRunningTest()) {
			enableLogging = enableLoggingOverride;
			saveExceptionLogs= saveExceptionLogsOverride;
			saveAllLogs = saveAllLogsOverride;
			saveUserLogs = saveExceptionLogsOverride;
			classNamesToLog = classNamesToLogOverride;
			return;
		}

		enableLogging = false;
		saveAllLogs = false;
		saveExceptionLogs = false;
		saveUserLogs = false;
		classNamesToLog = '';

		LoggerConfig__mdt setting = [SELECT IsActive__c, LogsToSave__c, ClassNames__c, AdditionalClassNames__c FROM LoggerConfig__mdt WHERE IsActive__c = true ORDER BY DeveloperName ASC LIMIT 1];
		if (setting == null) {
			enableLogging = false;
			return;
		}
		enableLogging = true;

		String logsToSave = setting.LogsToSave__c;
		switch on logsToSave {
			when 'AllLogs' {
				saveAllLogs = true;
			}
			when 'ExceptionOnly' {
				saveExceptionLogs = true;
			}
			when 'UserLogs' {
				saveUserLogs = true;
			}
			when 'ByClass' {
				classNamesToLog =  setting.ClassNames__c + setting.AdditionalClassNames__c;
			}
		}
		loggerConfigInstance = this;
	}

	public static LoggerConfig getConfig() {
		if (loggerConfigInstance == null) {
			loggerConfigInstance = new LoggerConfig();
		}
		return loggerConfigInstance;
	}
}